name: Tests

on: [push, pull_request]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.2'

    - uses: actions/checkout@v4

    - name: Install composer dependencies
      run: composer install --no-scripts

    - name: Prepare Laravel application
      run: |
        cp .env.ci .env
        php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Install frontend dependecies
      run: |
        npm ci
        npm run dev

    - name: Run testsuit
      run: php artisan test
